# MM-StoryAgent Configuration with Reference Images
# This configuration demonstrates character consistency using reference images

story_dir: &story_dir generated_stories/reference_example

# Story generation
story_writer:
    tool: qa_outline_story_writer
    cfg:
        max_conv_turns: 3
        num_outline: 4
        temperature: 0.5
        llm: qwen
    params:
        story_topic: "Adventure of two friends: Alice and Bob explore a magical forest"
        main_role: "Alice, a curious girl with brown hair"
        scene: "A magical forest with talking animals"

# Enhanced image generation with reference images
image_generation:
    tool: story_diffusion_t2i
    cfg:
        num_turns: 3
        model_name: stabilityai/stable-diffusion-xl-base-1.0  # API endpoint model
        height: &image_height 512
        width: &image_width 1024
        llm: qwen
        reference_processor: reference_image_processor  # Use advanced processor
    params:
        seed: 112536
        guidance_scale: 7.5  # Adjusted for API
        style_name: "Storybook"
        # Reference images for character consistency
        reference_images:
            - image_path: "path/to/alice_reference.jpg"
              character_name: "Alice"
            - image_path: "path/to/bob_reference.jpg"
              character_name: "Bob"
            - image_path: "path/to/forest_animal.jpg"
              character_name: "Forest Animal"

# Sound generation
sound_generation:
    tool: audioldm2_t2a
    cfg:
        num_turns: 3
        model_name: cvssp/audioldm2  # API endpoint model
        sample_rate: &sample_rate 16000
        llm: qwen
    params:
        guidance_scale: 3.5
        seed: 0
        ddim_steps: 100  # Reduced for API efficiency
        n_candidate_per_text: 1  # Reduced for API efficiency

# Speech generation
speech_generation:
    tool: cosyvoice_tts
    cfg:
        sample_rate: *sample_rate
    params:
        voice: longyuan

# Music generation
music_generation:
    tool: musicgen_t2m
    cfg:
        llm: qwen
        num_turns: 3
        model_name: facebook/musicgen-medium  # API endpoint model
        sample_rate: *sample_rate
    params:
        duration: 30.0

# Video composition
video_compose:
    tool: slideshow_video_compose
    cfg:
        {}
    params:
        height: *image_height
        width: *image_width
        story_dir: *story_dir
        fps: 8
        audio_sample_rate: *sample_rate
        audio_codec: mp3
        caption:
            font: resources/font/msyh.ttf
            fontsize: 32
            color: white
            max_length: 50
        slideshow_effect:
            bg_speech_ratio: 0.6
            sound_volume: 0.6
            music_volume: 0.5
            fade_duration: 0.8
            slide_duration: 0.4
            zoom_speed: 0.5
            move_ratio: 0.9